name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install .[dev]
      - name: Ruff format
        run: ruff format --check .
      - name: Ruff lint
        run: ruff check .
      - name: Mypy
        run: mypy --strict --exclude build .
      - name: Pytest
        run: pytest tests/
